apiVersion: v2
name: grafana
version: 1.16.0
dependencies:
  - name: default
    version: 0.1.3
    repository: http://chart.dmgsoftware.com.br/
    
  - name: prometheus-node-exporter
    version: "4.24.0"
    repository: https://prometheus-community.github.io/helm-charts
    

  - name: kube-state-metrics
    version: "5.17.0"
    repository: https://prometheus-community.github.io/helm-charts

  - name: grafana
    version: "10.0.0"                          
    repository: https://grafana.github.io/helm-charts
    