# Configuração completa para o chart default para evitar erros de nil pointer
default:
  enabled: false
  storageClass:
    create: false  # Fornece valor padrão para evitar nil pointer
    name: ""
  persistentVolume:
    create: false  # Fornece valor padrão
    enabled: false
  persistence:
    enabled: false
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

prometheus:
  enabled: true
  replicaCount: 1

  image:
    repository: prom/prometheus
    pullPolicy: IfNotPresent
    tag: "v2.52.0"

  service:
    enabled: true
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.dyego.lab
        
    tls: []

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # DESCOMENTADO e com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi

  kubeStateMetrics:
    enabled: true
    fullnameOverride: prometheus-kube-state-metrics

  nodeExporter:
    enabled: true
    fullnameOverride: prometheus-node-exporter

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80



  securityContext:
    runAsUser: 0

grafana:
  enabled: true
  replicaCount: 1

  image:
    repository: grafana/grafana
    tag: "10.0.0"
    pullPolicy: IfNotPresent

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # Com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi

  adminUser: admin
  adminPassword: "@Dyego050291#"

  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    # Formato correto para o chart Grafana
    hosts:
      - grafana.dyego.lab  # Lista de strings simples
    # Ou alternativamente, se não funcionar:
    # host: grafana.dyego.lab
    # path: /

# Configuração global para evitar problemas adicionais
global:
  storageClass:
    create: false