default:
  enabled: false
  storageClass:
    create: false  # Fornece valor padrão para evitar nil pointer
    name: ""
  persistentVolume:
    create: false  # Fornece valor padrão
    enabled: false
  persistence:
    enabled: false
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

# --- PROMETHEUS ---
prometheus:
  enabled: true

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # Com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi

  service:
    enabled: true
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.dyego.lab
        
    tls: []

 

 
# --- GRAFANA ---
grafana:
  enabled: true 

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # Com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi

  adminUser: admin
  adminPassword: "@Dyego050291#"

  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    # Formato correto para o chart Grafana
    hosts:
      - grafana.dyego.lab  # Lista de strings simples
    # Ou alternativamente, se não funcionar:
    # host: grafana.dyego.lab
    # path: /

# --- NODE EXPORTER ---
prometheus-node-exporter:
  enabled: true
  serviceMonitor:
    enabled: true

# --- KUBE STATE METRICS ---
kube-state-metrics:
  enabled: true

# Configuração global para evitar problemas adicionais
global:
  storageClass:
    create: false