# --- PROMETHEUS ---
prometheus:
  enabled: true
  image:
    repository: quay.io/prometheus-operator/prometheus-config-reloader
    tag: v0.85.0  # Versão específica do Prometheus
    pullPolicy: IfNotPresent

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # Com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi
    
  service:
    enabled: true
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.dyego.lab
        
    tls: []

 

 
# --- GRAFANA ---
grafana:
  enabled: true 

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # Com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi

  adminUser: admin
  adminPassword: "@Dyego050291#"

  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    # Formato correto para o chart Grafana
    hosts:
      - grafana.dyego.lab  # Lista de strings simples
    # Ou alternativamente, se não funcionar:
    # host: grafana.dyego.lab
    # path: /

# --- NODE EXPORTER ---
prometheus-node-exporter:
  enabled: true
  serviceMonitor:
    enabled: true

# --- KUBE STATE METRICS ---
kube-state-metrics:
  enabled: true

