# --- PROMETHEUS ---
prometheus:
  enabled: true
  
  alertmanager:
    enabled: false   # <--- desabilita o Alertmanager 

  service:
    enabled: true
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.dyego.lab
        
    tls: []

 
#----Server Prometheus----

server:  
  persistentVolume:
    enabled: true
    storageClassName: "nfs-client"
    accessModes:
      - ReadWriteMany
    size: 10Gi
 
# --- GRAFANA ---
grafana:
  enabled: true 

  persistence:
    enabled: true
    storageClassName: "nfs-client"  # Com aspas
    accessModes:
      - ReadWriteMany
    size: 10Gi

  adminUser: admin
  adminPassword: "@Dyego050291#"

  service:
    enabled: true
    type: ClusterIP
    port: 3000

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    # Formato correto para o chart Grafana
    hosts:
      - grafana.dyego.lab  # Lista de strings simples
    # Ou alternativamente, se não funcionar:
    # host: grafana.dyego.lab
    # path: /

# --- NODE EXPORTER ---
prometheus-node-exporter:
  enabled: true
  serviceMonitor:
    enabled: true

# --- KUBE STATE METRICS ---
kube-state-metrics:
  enabled: true

